vars:
  - params.yaml

stages:

  fetch_data_pol_subjects:
    cmd: >-
      python ${scripts.fetch_data}
      -i "${data.raw_data.pol.subjects}"
      -o "${data.interim_data.pol.subjects}"
    deps:
      - ${scripts.fetch_data}
      - ${data.raw_data.pol.subjects}
    outs:
      - ${data.interim_data.pol.subjects}

  fetch_data_pol_scolarship:
    cmd: >-
      python ${scripts.fetch_data}
      -i "${data.raw_data.pol.scholarship}"
      -o "${data.interim_data.pol.scholarship}"
    deps:
      - ${scripts.fetch_data}
      - ${data.raw_data.pol.scholarship}
    outs:
      - ${data.interim_data.pol.scholarship}

  fetch_data_pol_personal_data:
    cmd: >-
      python ${scripts.fetch_data}
      -i "${data.raw_data.pol.personal_data}"
      -o "${data.interim_data.pol.personal_data}"
    deps:
      - ${scripts.fetch_data}
      - ${data.raw_data.pol.personal_data}
    outs:
      - ${data.interim_data.pol.personal_data}

  etl_pol_subjects:
    cmd: >-
      python "${scripts.etl.scolarship_&_subjects}"
      -i "${data.interim_data.pol.subjects}"
      -o "${data.processed_data.pol.subjects}"
    deps:
      - ${scripts.etl.scolarship_&_subjects}
      - ${data.interim_data.pol.subjects}
      - Code/keys.py
    outs:
      - ${data.processed_data.pol.subjects}

  etl_pol_scolarship:
    cmd: >-
      python "${scripts.etl.scolarship_&_subjects}"
      -i "${data.interim_data.pol.scholarship}"
      -o "${data.processed_data.pol.scholarship}"
    deps:
      - ${scripts.etl.scolarship_&_subjects}
      - ${data.interim_data.pol.scholarship}
      - Code/keys.py
    outs:
      - ${data.processed_data.pol.scholarship}

  etl_pol_personal_data:
    cmd: >-
      python ${scripts.etl.personal_data}
      -i "${data.interim_data.pol.personal_data}" "${data.processed_data.pol.subjects}"
      -o "${data.processed_data.pol.personal_data}"
    deps:
      - ${scripts.etl.personal_data}
      - ${data.interim_data.pol.personal_data}
      - ${data.processed_data.pol.subjects}
      - Code/keys.py
    outs:
      - ${data.processed_data.pol.personal_data}

  feat_eng_pol_personal_data:
    cmd: >-
      python ${scripts.feat_eng.personal_data_script}
      -i "${data.processed_data.pol.personal_data}" "${data.processed_data.pol.scholarship}"
      -o "${data.analys_data.personal_data.pol}"
    deps:
      - ${scripts.feat_eng.personal_data_script}
      - ${data.processed_data.pol.personal_data}
      - ${data.processed_data.pol.scholarship}
      - Code/keys.py
    outs:
      - ${data.analys_data.personal_data.pol}

  feat_eng_pol_2nd_quad:
    cmd: >-
      python ${scripts.feat_eng.quadrimesters_script}
      -i "${data.analys_data.personal_data.pol}" "${data.processed_data.pol.subjects}" "${data.processed_data.pol.scholarship}"
      -o "${data.analys_data.2nd_quad.pol}"
      -c 1
      -q 2
    deps:
      - ${scripts.feat_eng.quadrimesters_script}
      - ${data.analys_data.personal_data.pol}
      - ${data.processed_data.pol.subjects}
      - ${data.processed_data.pol.scholarship}
      - Code/keys.py
    outs:
      - ${data.analys_data.2nd_quad.pol}
