wdir:
  fetch_data: "Code/data_acquisition_and_understanding/fetch_data/"
  etl:
    scolarship_&_subjects: "Code/data_acquisition_and_understanding/etl/etl_scolarship_and_subjects/"
    personal_data: "Code/data_acquisition_and_understanding/etl/etl_personal_data/"
  feat_eng:
    personal_data_script: "Code/feature_engineering/"
    quadrimesters_script: "Code/feature_engineering/"
  feat_sel: "Code/feature_selection/"
  analys: "Code/analysis_and_modeling/"

scripts:
  fetch_data: "Code/data_acquisition_and_understanding/fetch_data/fetch_data.py"
  etl:
    scolarship_&_subjects: "Code/data_acquisition_and_understanding/etl/etl_scolarship_and_subjects/etl_scolarship_and_subjects.py"
    personal_data: "Code/data_acquisition_and_understanding/etl/etl_personal_data/etl_personal_data.py"
  feat_eng:
    personal_data_script: "Code/feature_engineering/personal_data_feat_eng.py"
    quadrimesters_script: "Code/feature_engineering/quadrimesters_feat_eng.py"
  feat_sel: "Code/feature_selection/feat_sel.py"
  analys_personal_data: "Code/analysis_and_modeling/models_comparison.py"
  analys_personal_data_hyp_tunning: "Code/analysis_and_modeling/models_personal_data_hyp_tunning.py"
  analys_personal_data_ensemble: "Code/analysis_and_modeling/models_personal_data_ensemble.py"
  analys_quadrimesters_hyp_tunning: "Code/analysis_and_modeling/models_quadrimesters_hyp_tunning.py"
  analys_quadrimesters_ensemble: "Code/analysis_and_modeling/models_quadrimesters_ensemble.py"

model:
  "1": "1st_model"
  "2": "2nd_model"
  "3": "3rd_model"
  "4": "4th_model"
  "5": "5th_model"
  "6": "6th_model"
  "7": "7th_model"
  "8": "8th_model"

data:
  raw_data:
    pol:
      subjects: "Data/Raw/qualifications.xls"
      scholarship: "Data/Raw/scolarship.xls"
      personal_data: "Data/Raw/enrolment.xls"

  interim_data:
    pol:
      subjects: "Data/Interim/subjects.csv"
      scholarship: "Data/Interim/scholarship.csv"
      personal_data: "Data/Interim/personal_data.csv"

  processed_data:
    pol:
      subjects: "Data/Processed/pr_subjects.csv"
      scholarship: "Data/Processed/pr_scolarship.csv"
      personal_data: "Data/Processed/pr_personal_data.csv"

  analys_data:
    personal_data:
      pol: "Data/For_analysis_and_modeling/personal_data/analys_personal_data.csv"
    1st_quad:
      pol:  "Data/For_analysis_and_modeling/1st_quadrimester/analys_personal_data.csv"
    2nd_quad:
      pol:  "Data/For_analysis_and_modeling/2nd_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/2nd_quadrimester/analys_teaching_personal_data.csv"
    3rd_quad:
      pol:  "Data/For_analysis_and_modeling/3rd_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/3rd_quadrimester/analys_teaching_personal_data.csv"
    4th_quad:
      pol:  "Data/For_analysis_and_modeling/4th_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/4th_quadrimester/analys_teaching_personal_data.csv"
    5th_quad:
      pol:  "Data/For_analysis_and_modeling/5th_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/5th_quadrimester/analys_teaching_personal_data.csv"
    6th_quad:
      pol:  "Data/For_analysis_and_modeling/6th_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/6th_quadrimester/analys_teaching_personal_data.csv"
    7th_quad:
      pol:  "Data/For_analysis_and_modeling/7th_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/7th_quadrimester/analys_teaching_personal_data.csv"
    8th_quad:
      pol:  "Data/For_analysis_and_modeling/8th_quadrimester/analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/8th_quadrimester/analys_teaching_personal_data.csv"

  final_analys_data:
    personal_data:
      pol: "Data/For_analysis_and_modeling/personal_data/final_analys_personal_data.csv"
    1st_quad:
      pol:  "Data/For_analysis_and_modeling/1st_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/1st_quadrimester/final_analys_teaching_personal_data.csv"
    2nd_quad:
      pol:  "Data/For_analysis_and_modeling/2nd_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/2nd_quadrimester/final_analys_teaching_personal_data.csv"
    3rd_quad:
      pol:  "Data/For_analysis_and_modeling/3rd_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/3rd_quadrimester/final_analys_teaching_personal_data.csv"
    4th_quad:
      pol:  "Data/For_analysis_and_modeling/4th_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/4th_quadrimester/final_analys_teaching_personal_data.csv"
    5th_quad:
      pol:  "Data/For_analysis_and_modeling/5th_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/5th_quadrimester/final_analys_teaching_personal_data.csv"
    6th_quad:
      pol:  "Data/For_analysis_and_modeling/6th_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/6th_quadrimester/final_analys_teaching_personal_data.csv"
    7th_quad:
      pol:  "Data/For_analysis_and_modeling/7th_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/7th_quadrimester/final_analys_teaching_personal_data.csv"
    8th_quad:
      pol:  "Data/For_analysis_and_modeling/8th_quadrimester/final_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/8th_quadrimester/final_analys_teaching_personal_data.csv"

  pred_analys_data:
    personal_data:
      pol: "Data/For_analysis_and_modeling/personal_data/pred_analys_personal_data.csv"
    1st_quad:
      pol: "Data/For_analysis_and_modeling/1st_quadrimester/pred_analys_personal_data.csv"
    2nd_quad:
      pol: "Data/For_analysis_and_modeling/2nd_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/2nd_quadrimester/pred_analys_teaching_personal_data.csv"
    3rd_quad:
      pol: "Data/For_analysis_and_modeling/3rd_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/3rd_quadrimester/pred_analys_teaching_personal_data.csv"
    4th_quad:
      pol: "Data/For_analysis_and_modeling/4th_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/4th_quadrimester/pred_analys_teaching_personal_data.csv"
    5th_quad:
      pol: "Data/For_analysis_and_modeling/5th_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/5th_quadrimester/pred_analys_teaching_personal_data.csv"
    6th_quad:
      pol: "Data/For_analysis_and_modeling/6th_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/6th_quadrimester/pred_analys_teaching_personal_data.csv"
    7th_quad:
      pol: "Data/For_analysis_and_modeling/7th_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/7th_quadrimester/pred_analys_teaching_personal_data.csv"
    8th_quad:
      pol: "Data/For_analysis_and_modeling/8th_quadrimester/pred_analys_personal_data.csv"
      teach: "Data/For_analysis_and_modeling/8th_quadrimester/pred_analys_teaching_personal_data.csv"
